### ISSUE TITLE
Error in reusable transition getPartyList on H2 databse

### ISSUE THREAD

**Issue by igorgallingani** [moqui/SimpleScreens#51] opened 2017-05-11 10:15 UTC
Caused by: org.moqui.entity.EntityException: SQL Exception with statement:
SELECT DISTINCT PTY.PARTY_ID, PTY.PSEUDO_ID, ORG.ORGANIZATION_NAME, PER.FIRST_NAME, PER.LAST_NAME FROM (PARTY PTY LEFT OUTER JOIN PERSON PER ON PTY.PARTY_ID = PER.PARTY_ID LEFT OUTER JOIN ORGANIZATION ORG ON PTY.PARTY_ID = ORG.PARTY_ID) WHERE ((PTY.DISABLED = ? OR PTY.DISABLED  IS NULL) AND (UPPER(PTY.PARTY_ID) LIKE ? OR UPPER(PTY.PSEUDO_ID) LIKE ? OR UPPER(PER.FIRST_NAME) LIKE ? OR UPPER(PER.LAST_NAME) LIKE ? OR UPPER(ORG.ORGANIZATION_NAME) LIKE ?)) ORDER BY UPPER(PER.FIRST_NAME) ASC, UPPER(PER.LAST_NAME) ASC, UPPER(ORG.ORGANIZATION_NAME) ASC OFFSET 0 ROWS FETCH FIRST 20 ROWS ONLY; 
org.h2.jdbc.JdbcSQLException: Order by expression "UPPER(PER.FIRST_NAME)" must be in the result list in this case; SQL statement:

Possible solution:
remove ^ from order-by
<order-by field-name="^firstName,^lastName,^organizationName"/>

**Comment by jonesde** [comment] 2017-05-11 17:23
Thank you for reporting this, it is fixed in commit #44734bd.

Similar changes had to be made in the find#Party service because it also uses a distinct select.

On a side note: for SimpleScreens, PopCommerce, HiveMind, and some custom stuff I'm working on for clients most things are moving from getPartyList to the more flexible (and faster) ElasticSearch based searchPartyList. That is also part of the reason I haven't run into this though it is easy to reproduce.

**Closed by jonesde** 2017-05-11 17:23 UTC
